### ISSUE TITLE
Router Scan?

### ISSUE THREAD

**Issue by hasanalizxc** [Virgula0/TheReaver#1]
Dear Virgula0,

Hope you are fine. Do you use Router Scan 2.60 features?

**Comment by Virgula0** [comment]
Nope. The only dependecies for default wps pins are took from airgeddon project local db pins. I'll release it soon, wait for it

**Comment by hasanalizxc** [comment]
Please when you release comment for income e-mail

**Comment by Virgula0** [comment]
You can follow me and get updated about what i'm doing every time :)

**Comment by hasanalizxc** [comment]
I will follow you be sure :)
